[services]
solver = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
mediator = ["0x7B49d6ee530B0A538D26E344f3B02E79ACa96De2"]
api_host = "https://api-testnet.lilypad.tech/"

[web3]
rpc_url = "ws://wss.orbit.arsenum.com"
chain_id = 95873066572
controller_address = "0xdF2bc8d64A869eF4605BA821cE7183A702D5Bf72"
payments_address = "0xE7FdFfD56797a6E6024a09bd168effCa6C5208cE"
storage_address = "0xDf9EAf5f1020d75c502DC66FFCC43a634E10017b"
users_address = "0x3f4048eBDB5C853EDBe30843f8e8e6CC9aFfAbFe"
token_address = "0x2B0722b2C623b19aDA2ec56D50487203a7475C38"
mediation_address = "0xe4d7E958651fFc58e8D3985BC193198BB5Ff2af7"
jobcreator_address = "0x5a6d1D3E7e16Dc69d61232A395773301b4580849"
pow_address = "0x7cFA21dB253afBcD9AaCf2dE58FC3C0e9D1a9149"

[ipfs]
addr = "/dns4/ipfs/tcp/5001"

[telemetry]
url = "https://observe.lilypad.tech"
token = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJ1c2VyIjoicmVzb3VyY2UtcHJvdmlkZXIifQ.n36M_ngwC4XPQ_pEkkWAnPiOinnx6-0VO1v_WgCTUEERD7b_p9KHCU6SY5bUdFh5UXRZHAhc1gfyc7rjAnmeDQ"

[offer]
modules = "github.com/Lilypad-Tech/lilypad-module-cowsay:v0.0.4, https://github.com/Lilypad-Tech/lilypad-module-sdxl-pipeline:v1.2.0"

[disable]
telemetry=1
